# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all

ackerman = User.create!(username: 'ackerman', first_name: 'Mr.', last_name: 'Ackerman', age: 25, password: 'reddwarf', email: 'ackerman@reddwarf.com')
angus = User.create!(username: 'securityOfficerThornton', first_name: 'Angus', last_name: 'Thornton', age: 25, password: 'reddwarf', email: 'athornton@reddwarf.com')
arnold = User.create!(username: 'smegHead', first_name: 'Arnold', last_name: 'Rimmer', age: 25, password: 'reddwarf', email: 'arimmer@reddwarf.com')
bexley = User.create!(username: 'bLister', first_name: 'Bexley', last_name: 'Lister', age: 25, password: 'reddwarf', email: 'blister@reddwarf.com')
bradley = User.create!(username: 'officerBradley', first_name: 'Officer', last_name: 'Bradley', age: 25, password: 'reddwarf', email: 'obradley@reddwarf.com')
brannigan = User.create!(username: 'officerBrannigan', first_name: 'Officer', last_name: 'Brannigan', age: 25, password: 'reddwarf', email: 'obrannigan@reddwarf.com')
buchan = User.create!(username: 'scienceOfficerBuchan', first_name: 'Officer', last_name: 'Buchan', age: 25, password: 'reddwarf', email: 'obuchan@reddwarf.com')
carol_b = User.create!(username: 'exOBrown', first_name: 'Carol', last_name: 'Brown', age: 25, password: 'reddwarf', email: 'cbrown@reddwarf.com')
carol_m = User.create!(username: 'cMcCauley', first_name: 'Carol', last_name: 'McCauley', age: 25, password: 'reddwarf', email: 'cmccauley@reddwarf.com')
caroline = User.create!(username: 'supplyOfficerCarmen', first_name: 'Caroline', last_name: 'Carmen', age: 25, password: 'reddwarf', email: 'ccarmen@reddwarf.com')
cat = User.create!(username: 'cat', first_name: 'The', last_name: 'Cat', age: 25, password: 'reddwarf', email: 'tcat@reddwarf.com')
chen = User.create!(username: 'chen', first_name: 'Chen', last_name: 'Crew', age: 25, password: 'reddwarf', email: 'chen@reddwarf.com')
chippy = User.create!(username: 'chippy', first_name: 'Chippy', last_name: 'Medical Implant Device', age: 25, password: 'reddwarf', email: 'chippy@reddwarf.com')
chocolate_ai_vm = User.create!(username: 'coco', first_name: 'The', last_name: 'Chocolate Dispenser', age: 25, password: 'reddwarf', email: 'tcdispenser@reddwarf.com')
dave = User.create!(username: 'dave', first_name: 'David', last_name: 'Lister', age: 25, password: 'reddwarf', email: 'dlister@reddwarf.com')
denton = User.create!(username: 'officerDenton', first_name: 'Officer', last_name: 'Denton', age: 25, password: 'reddwarf', email: 'odenton@reddwarf.com')
dispenser_16 = User.create!(username: 'dispenser16', first_name: 'Dispenser', last_name: '16', age: 25, password: 'reddwarf', email: 'dispenser16@reddwarf.com')
dispenser_23 = User.create!(username: 'dispenser23', first_name: 'Dispenser', last_name: '23', age: 25, password: 'reddwarf', email: 'dispenser23@reddwarf.com')
dispenser_34 = User.create!(username: 'dispenser34', first_name: 'Dispenser', last_name: '34', age: 25, password: 'reddwarf', email: 'dispenser34@reddwarf.com')
dispenser_55 = User.create!(username: 'dispenser55', first_name: 'Dispenser', last_name: '55', age: 25, password: 'reddwarf', email: 'dispenser55@reddwarf.com')
dispenser_402 = User.create!(username: 'dispenser402', first_name: 'Dispenser', last_name: '402', age: 25, password: 'reddwarf', email: 'dispenser402@reddwarf.com')
duane = User.create!(username: 'dDibbley', first_name: 'Duane', last_name: 'Dibbley', age: 25, password: 'reddwarf', email: 'ddibbley@reddwarf.com')
frank_h = User.create!(username: 'theCaptain', first_name: 'Frank', last_name: 'Hollister', age: 25, password: 'reddwarf', email: 'fhollister@reddwarf.com')
frank_s = User.create!(username: 'engineerSaunders', first_name: 'Frank', last_name: 'Saunders', age: 25, password: 'reddwarf', email: 'fsaunders@reddwarf.com')
frank_t = User.create!(username: 'officerTodhunter', first_name: 'Frank', last_name: 'Todhunter', age: 25, password: 'reddwarf', email: 'ftodhunter@reddwarf.com')
harrison = User.create!(username: 'hologramHarrison', first_name: 'Ms.', last_name: 'Harrison', age: 25, password: 'reddwarf', email: 'hharrison@reddwarf.com')
harris = User.create!(username: 'headbangerHarris', first_name: 'Headbanger', last_name: 'Harris', age: 25, password: 'reddwarf', email: 'hharris@reddwarf.com')
henri = User.create!(username: 'navigationOfficerDubois', first_name: 'Henri', last_name: 'Dubois', age: 25, password: 'reddwarf', email: 'hdubois@reddwarf.com')
hilly = User.create!(username: 'hilly', first_name: 'Hilly', last_name: 'IQ 6000', age: 25, password: 'reddwarf', email: 'hilly@reddwarf.com')
holly = User.create!(username: 'hol', first_name: 'Holly', last_name: 'IQ 6000', age: 25, password: 'reddwarf', email: 'holly@reddwarf.com')
jim = User.create!(username: 'jLister', first_name: 'Jim', last_name: 'Lister', age: 25, password: 'reddwarf', email: 'jlister@reddwarf.com')
karen = User.create!(username: 'drNewton', first_name: 'Karen', last_name: 'Newton', age: 25, password: 'reddwarf', email: 'knewton@reddwarf.com')
katerina = User.create!(username: 'ScienceOfficerBartokovsky', first_name: 'Katerina', last_name: 'Bartokovsky', age: 25, password: 'reddwarf', email: 'kbartokovsky@reddwarf.com')
knot = User.create!(username: 'knot', first_name: 'Mr.', last_name: 'Knot', age: 25, password: 'reddwarf', email: 'mknot@reddwarf.com')
kochanskis_roommate = User.create!(username: 'kochanskisRoommate', first_name: 'Roommate', last_name: 'of Kochanski', age: 25, password: 'reddwarf', email: 'roommate@reddwarf.com')
kristine = User.create!(username: 'kris', first_name: 'Kristine', last_name: 'Kochanski', age: 25, password: 'reddwarf', email: 'kkochanski@reddwarf.com')
kryton = User.create!(username: 'kryton', first_name: 'Kryton', last_name: '4000 Series Android', age: 25, password: 'reddwarf', email: 'kryton@reddwarf.com')
lift_hostess = User.create!(username: 'liftHostess', first_name: 'Lift', last_name: 'Hostess', age: 25, password: 'reddwarf', email: 'lhostess@reddwarf.com')
lucas = User.create!(username: 'drMcClaren', first_name: 'Lucas', last_name: 'McClaren', age: 25, password: 'reddwarf', email: 'lmcclaren@reddwarf.com')
macwilliams = User.create!(username: 'macWilliams', first_name: 'Mr.', last_name: 'MacWilliams', age: 25, password: 'reddwarf', email: 'macwilliams@reddwarf.com')
mcqueen = User.create!(username: 'flightCoordinator', first_name: 'Mr.', last_name: 'McQueen', age: 25, password: 'reddwarf', email: '@reddwarf.com')
medibot = User.create!(username: 'medi-bot', first_name: 'Medi-Bot', last_name: 'Medicomp', age: 25, password: 'reddwarf', email: 'medi-bot@reddwarf.com')
med_orderly = User.create!(username: 'medOrderly', first_name: 'The', last_name: 'Medical Orderly', age: 25, password: 'reddwarf', email: 'oderly@reddwarf.com')
petersen = User.create!(username: 'petersen', first_name: 'Olaf', last_name: 'Petersen', age: 25, password: 'reddwarf', email: 'opetersen@reddwarf.com')
parkinson = User.create!(username: 'scienceOfficerParkinson', first_name: 'Officer', last_name: 'Parkinson', age: 25, password: 'reddwarf', email: 'soparkinson@reddwarf.com')
patricia = User.create!(username: 'supplyOfficerCarling', first_name: 'Patricia', last_name: 'Carling', age: 25, password: 'reddwarf', email: 'pcarling@reddwarf.com')
pessell = User.create!(username: 'pessell', first_name: 'Mr.', last_name: 'Pessell', age: 25, password: 'reddwarf', email: 'pessell@reddwarf.com')
petrovich = User.create!(username: 'sOPetrovich', first_name: 'Officer', last_name: 'Petrovich', age: 25, password: 'reddwarf', email: 'opetrovich@reddwarf.com')
queeg = User.create!(username: 'queeg', first_name: 'Queeg', last_name: '500', age: 25, password: 'reddwarf', email: 'queeg@reddwarf.com')
rachael = User.create!(username: 'rachael', first_name: 'Rachael', last_name: 'Doll', age: 25, password: 'reddwarf', email: 'rdoll@reddwarf.com')
sam = User.create!(username: 'dkSgtMurray', first_name: 'Sam', last_name: 'Murray', age: 25, password: 'reddwarf', email: 'smurray@reddwarf.com')
sc_controller = User.create!(username: 'sCController', first_name: 'Second Ground', last_name: 'Controller', age: 25, password: 'reddwarf', email: 'sccontroller@reddwarf.com')
selby = User.create!(username: 'selby', first_name: 'Selby', last_name: 'Crew', age: 25, password: 'reddwarf', email: 'selby@reddwarf.com')
snacky = User.create!(username: 'snacky', first_name: 'Snacky', last_name: 'Dispenser', age: 25, password: 'reddwarf', email: 'snacky@reddwarf.com')
tt = User.create!(username: 'tT', first_name: 'Tony', last_name: 'T', age: 25, password: 'reddwarf', email: 'tt@reddwarf.com')
talia = User.create!(username: 'sisterGarrett', first_name: 'Talia', last_name: 'Garrett', age: 25, password: 'reddwarf', email: 'tgarrett@reddwarf.com')
talkie = User.create!(username: 'talkieToaster', first_name: 'Talkie', last_name: 'Toaster', age: 25, password: 'reddwarf', email: 'ttoaster@reddwarf.com')
tim = User.create!(username: 'chefTim', first_name: 'Tim', last_name: 'C', age: 25, password: 'reddwarf', email: 'cheftim@reddwarf.com')
weiner = User.create!(username: 'hologramTechWeiner', first_name: 'Hologram Technician', last_name: 'Weiner', age: 25, password: 'reddwarf', email: 'htweiner@reddwarf.com')
yvonne = User.create!(username: 'yMcGruder', first_name: 'Yvonne', last_name: 'McGruder', age: 25, password: 'reddwarf', email: 'ymcgruder@reddwarf.com')

bob = User.create!(username: 'skutterBob', first_name: 'Bob', last_name: 'Skutter', age: 25, password: 'reddwarf', email: 'bob@reddwarf.com')
madge = User.create!(username: 'skutterMadge', first_name: 'Madge', last_name: 'Skutter', age: 25, password: 'reddwarf', email: 'madge@reddwarf.com')
stabbim = User.create!(username: 'skutterStabbim', first_name: 'Stabbim', last_name: 'Skutter', age: 25, password: 'reddwarf', email: 'stabbim@reddwarf.com')
el_skutto = User.create!(username: 'skutterElSkutto', first_name: 'El Skutto', last_name: 'Skutter', age: 25, password: 'reddwarf', email: 'elskutto@reddwarf.com')
pinky = User.create!(username: 'skutterPinky', first_name: 'Pinky', last_name: 'Skutter', age: 25, password: 'reddwarf', email: 'pinky@reddwarf.com')
perky = User.create!(username: 'skutterPerky', first_name: 'Perky', last_name: 'Skutter', age: 25, password: 'reddwarf', email: 'perky@reddwarf.com')
skutter_4457 = User.create!(username: 'skutter4457', first_name: '4457', last_name: 'Skutter', age: 25, password: 'reddwarf', email: '4457@reddwarf.com')

Post.destroy_all

post_1 = Post.create!(user_id: talkie.id, subject: 'To toast or not to toast...', body: 'Would you like some toast?')